### ISSUE TITLE
Why redbug can not trace the un-exported function? What should I set?

### ISSUE THREAD

**Issue by tclugao** [massemanet/redbug#35]
as the following pic. the function handle is exported, and function select_option is not exported
![image](https://github.com/massemanet/redbug/assets/100250096/ea311479-f1b9-41da-b891-56cc4bfa9ec9)

**Comment by sebastiw** [comment]
Hi,
first of all you are running an old (more than 4 year old)  version of redbug.

New syntax would be something in the style of
```erlang
1> redbug:start(["nurse_call_callback_handler:select_option"], #{msgs => 1_000_000, time => 100_000}).
```

Anyway, without a minimal example or access to your module it is impossible to answer your question.

I would suggest two things: upgrade to latest redbug, or add the module `nurse_call_callback_handler` as example here.

**Comment by sebastiw** [comment]
please reopen if you have more issues.
