### ISSUE TITLE
target (node()) node to trace on -> target (node()|[node()]) node(s) to trace on 

### ISSUE THREAD

**Issue by ghost** [massemanet/redbug#5]
First off, thanks for making such an awesome library, I have so much fun using Redbug, thanks for that. 

A question - is it feasable to modify the behavior of rebug so it traces on multiple nodes? 

My issue is that I tend to run traces on Riak nodes, for learning, demos, and debugging live issues, but the events can execute on any of N+ machines, where N is normally more than 5 (recommended size of a Riak cluster.

I could drop down to traditional tracing, but it scares people (including me) as it doesn't with any of the Redbug safety mechanisms - as a consequence, I tend to just randomly pick nodes and hope they will see the events.

There is quite possibly a reason why this functionality wasn't implemented, so this issue is also asking if that is by design.

**Comment by russelldb** [comment]
Just about to open an issue when I saw this. I use `rpc:call(Node, redbug, start, [Trc, Opts])` to get the features you're looking for @bryanhuntesl, but would also very much appreciate a supported option for `target=nodes()`
